// This file was auto-generated by ML.NET Model Builder. 

using System;
using CourseRecommendationSystemML.Model;

namespace CourseRecommendationSystemML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Student_id = 1F,
                Course = @"EL101",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Gpa with predicted Gpa from sample data...\n\n");
            Console.WriteLine($"Student_id: {sampleData.Student_id}");
            Console.WriteLine($"Course: {sampleData.Course}");
            Console.WriteLine($"\n\nPredicted Gpa: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
